version: "2.4"

services:
  pingdirectory:
    image: arnaudlacour/m-arch:pd
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/liberica-musl-investigation.git
      - SERVER_PROFILE_PARENT=BASE
      - SERVER_PROFILE_BASE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASE_PATH=baseline/pingdirectory
      - PING_IDENTITY_DEVOPS_USER=ping-devops-liberica@pingidentity.com
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_KEY=${KEY}
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
